### ISSUE TITLE
Setup on Windows

### ISSUE THREAD

**Issue by ChristianOezelt** [acheronfail/xi-electron#13]
Hi, 
I am trying to set it up on Windows and am getting following Error message:

```
ENOENT: no such file or directory, lstat 'C:\Users\chris\OneDrive\Dokumente\GitHub\xi-electron\xi-editor\rust\target\release\xi-core'
```

What exactly are you trying to copy? ( the xi.exe or the whole folder? )

![image](https://user-images.githubusercontent.com/20471999/36072196-c1ddca4a-0f1b-11e8-823e-84f25b6357b7.png)

Thanks for your help :)

**Comment by acheronfail** [comment]
Ah, that's because I've only tested this on *unix OS's!

I updated the build script in 16fca37 let me know if that works for you :)

**Comment by acheronfail** [comment]
If you run into any issues building xi-core/plugins on Windows and find the solution let me know :) I currently don't have a Windows machine to test on atm, so any help in that regard would be appreciated.

**Comment by ChristianOezelt** [comment]
Well your fix worked, but the plugins won't compile
c/g++ cant find some default header file `stddef.h`

It is installed on my machine but i couldn't tell gcc/g++ to look for it and hence some dependency of a dependency won't compile.

Now I have a reason to get my Ubuntu VBox up to date :sweat_smile:

**Comment by ChristianOezelt** [comment]
@acheronfail a bit unrelated to this topic, but do you intend setting up a gitter channel, or something similar, for devs of this project?

**Comment by acheronfail** [comment]
Hmm that's not so good - unfortunately I wouldn't know where to start with a Windows machine.

Even if the plugins don't build, you should still be able to `yarn start` (it only depends on `xi-core`) but the text colours may not work since the `xi-syntect-plugin` is what defines all the styles, etc.

> a bit unrelated to this topic, but do you intend setting up a gitter channel, or something similar, for devs of this project?

Well, this project is primarily a frontend for [`xi-editor`](https://github.com/google/xi-editor), building issues like this should be routed there, or to their IRC channel at #xi on irc.mozilla.org. 
The issues you're facing are to do with scripting that build process, and ideally that shouldn't happen in this repository (one of the reasons I originally chose to submodule `xi-editor` was to have a stable experience in building it automatically, but it seems it doesn't do that on Windows at the moment).
So, for building issues you should see if someone has a similar problem on that repo or ask in their IRC.

In regards to this repository, I never intended to have a gitter/IRC channel or anything, but if enough people show some interest I would definitely do it. 👍

**Comment by acheronfail** [comment]
Closing since building xi-core is out of scope for this repository.
