### ISSUE TITLE
Provide a prebuilt Windows binary for the xi_editor

### ISSUE THREAD

**Issue by MH15** [acheronfail/xi-electron#15]
This would allow users on Windows to test/develop your frontend without needing to compile Rust which, on Windows, is a nightmare.

**Comment by acheronfail** [comment]
Sorry, this repository is dedicated to creating a web-based frontend for xi-editor, and things relating to providing prebuilt binaries of the core are out of scope (since they are subject to change, and shouldn't affect this frontend).

Feel free to make requests upstream (xi-editor) for providing prebuilt binaries.

> ... without needing to compile Rust which, on Windows, is a nightmare.

FWIW, I've never had any issues building Rust on windows using [rustup](https://rustup.rs/#). I highly recommend you use that tool if you're having issues on Windows platforms.
