### ISSUE TITLE
xi-syntect-plugin: "Permission denied"

### ISSUE THREAD

**Issue by baransu** [acheronfail/xi-electron#3]
First of all, great work with this project so far 🎉. It's a great starting point for any web based `xi-editor` frontend. 

I've updated `bin/install_core.sh` (https://github.com/Baransu/xi-electron/commit/ba8b71e8fbd10f3e392dd21da9be823b3d221ad3) to output plugins into `src/xi-plugins` directory because previously I was getting errors/warnings from `xi-core` about missing plugins.

Right now I'm stuck with this error from `xi-syntect-plugin` when opening new file:
<img width="691" alt="screen shot 2017-09-07 at 22 33 10" src="https://user-images.githubusercontent.com/9558691/30184081-0c81328c-941d-11e7-94b1-4068e23941fc.png">
It can be because of limited permissions on `xi-core` when starting it as a `child_process`. I thought that moving `xi-plugins` inside `xi-core` will solve the problem but it's the same.

Do you have any ideas how it can be solved?

**Comment by ghost** [comment]
You may have to modify your build method for the plugins.

Looks like `xi-core` is trying to spawn the directory instead of the plugin (you can't spawn a process on a directory, so that's probably why it says `"Permission denied"`).

    starting plugin at path "/Users/baransu/Documents/Elm/xi-electron/src/xi-plugins/xi-syntect-plugin"

If you navigate to that path, you'll see that it's a directory -- *not a binary*.

If you move the `xi-syntect-plugin` binary (which is inside that directory) to the `XI_PLUGIN_DIR` (i.e., replace the `xi-syntect-plugin` directory with the `xi-syntect-plugin` executable which is inside of it) then `xi` will be able to spawn it without an error.

I hope that makes sense, it's seems confusing because the directory name is the same as the executable within it. Basically, at the end, your `XI_PLUGIN_DIR` directory should look like this:

    src/xi-plugins
    ├── bracket_example.py
    ├── shouty.py
    ├── spellcheck.py
    └── xi-syntect-plugin

**Comment by baransu** [comment]
Thank you a lot. It works now 😃 
I haven't thought about providing executable instead of directory.
